name: Smart Versioning and Tagging

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for comparison

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Determine version bump type
        id: version-bump
        run: |
          # Get latest tag
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          echo "Current version: $LATEST_TAG"

          # Get commits since last tag (or all commits if no tag)
          if [ "$LATEST_TAG" != "v0.1.0" ]; then
            COMMITS_SINCE_LAST_TAG=$(git log $LATEST_TAG..HEAD --pretty=format:"%s")
          else
            COMMITS_SINCE_LAST_TAG=$(git log --pretty=format:"%s")
          fi

          # Initialize bump type as PATCH (default)
          BUMP_TYPE="PATCH"

          # Check commit messages for MAJOR/MINOR indicators
          if echo "$COMMITS_SINCE_LAST_TAG" | grep -qE '^(feat|break|major)(\(.*\))?!:'; then
            BUMP_TYPE="MAJOR"
          elif echo "$COMMITS_SINCE_LAST_TAG" | grep -qE '^(feat|feature)(\(.*\))?:'; then
            BUMP_TYPE="MINOR"
          fi

          # Fallback: Check file changes if no conventional commits
          if [ "$BUMP_TYPE" = "PATCH" ]; then
            CHANGED_FILES=$(git diff --name-only $LATEST_TAG HEAD -- .)
            if echo "$CHANGED_FILES" | grep -qE '^src/.*\.(ts|js|py|java)$'; then
              BUMP_TYPE="MINOR"
            fi
          fi

          echo "Detected change type: $BUMP_TYPE"
          echo "BUMP_TYPE=$BUMP_TYPE" >> $GITHUB_ENV

      - name: Calculate new version
        id: calculate-version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          TAG_NUM=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG_NUM"

          case "$BUMP_TYPE" in
            "MAJOR")
              NEW_MAJOR=$((MAJOR + 1))
              NEW_TAG="v$NEW_MAJOR.0.0"
              ;;
            "MINOR")
              NEW_MINOR=$((MINOR + 1))
              NEW_TAG="v$MAJOR.$NEW_MINOR.0"
              ;;
            *)
              NEW_PATCH=$((PATCH + 1))
              NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
              ;;
          esac

          echo "New version: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: release-notes
        run: |
          COMMITS_SINCE_TAG=$(git log $LATEST_TAG..HEAD --pretty=format:"%h %s")

          FEATURES=""
          FIXES=""
          CHORES=""

          while IFS= read -r line; do
            HASH=$(echo "$line" | awk '{print $1}')
            MESSAGE=$(echo "$line" | cut -d ' ' -f2-)
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "$HASH")

            while IFS=' ' read -r word rest; do
              case "$word" in
                feat:)
                  FEATURES+="- **$rest** ([${HASH}](https://github.com/${{ github.repository }}/commit/${HASH}))\n  - 📂 Files changed: \`$CHANGED_FILES\`\n"
                  ;;
                fix:)
                  FIXES+="- **$rest** ([${HASH}](https://github.com/${{ github.repository }}/commit/${HASH}))\n  - 📂 Files changed: \`$CHANGED_FILES\`\n"
                  ;;
                chore:)
                  CHORES+="- **$rest** ([${HASH}](https://github.com/${{ github.repository }}/commit/${HASH}))\n  - 📂 Files changed: \`$CHANGED_FILES\`\n"
                  ;;
              esac
            done <<< "$MESSAGE"

          done <<< "$COMMITS_SINCE_TAG"

          RELEASE_NOTES="## 🚀 $NEW_TAG Release Notes\n"

          if [[ -n "$FEATURES" ]]; then RELEASE_NOTES+="### 🆕 New Features\n$FEATURES\n"; fi
          if [[ -n "$FIXES" ]]; then RELEASE_NOTES+="### 🛠 Fixes\n$FIXES\n"; fi
          if [[ -n "$CHORES" ]]; then RELEASE_NOTES+="### 🔧 Maintenance & Documentation\n$CHORES\n"; fi

          if [[ -z "$FEATURES" && -z "$FIXES" && -z "$CHORES" ]]; then
            RELEASE_NOTES+="No significant changes.\n"
          fi

          echo -e "$RELEASE_NOTES" > release_notes.md
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          NEW_TAG: ${{ env.NEW_TAG }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
