name: Auto Tagging on Commit

on:
  push:
    branches:
      - main  # Trigger this workflow on commits to the `main` branch

jobs:
  create-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the action has permission to push tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Bachhamba Khaireddine"
          git config user.email "khaireddine.bachhamba@ept.ucar.tn"

      - name: Get latest version
        id: version
        run: |
          # Check if there are any tags at all
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")  # Default to v0.0.0 if no tags exist
          TAG_NUM=$(echo $TAG | sed 's/v//')  # Strip 'v' if present
          IFS='.' read -r -a VERSION_PARTS <<< "$TAG_NUM"  # Split version into major, minor, patch

          # Increment the patch version (you can adjust this to major or minor if needed)
          PATCH=${VERSION_PARTS[2]}
          NEW_PATCH=$((PATCH + 1))

          NEW_TAG="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"  # Generate new tag (e.g., v1.0.1)
          echo "New version: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          NEW_TAG: ${{ env.NEW_TAG }}
