name: Auto Versioning and Tagging

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Bachhamba Khaireddine"
          git config user.email "khaireddine.bachhamba@ept.ucar.tn"
      
      - name: Get the latest tag (if any)
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.1.0")  # Default to v0.1.0 if no tags exist
          echo "Latest Tag: $TAG"
          TAG_NUM=$(echo $TAG | sed 's/v//')  # Remove 'v' from tag
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG_NUM"  # Split version into MAJOR, MINOR, PATCH
          NEW_PATCH=$((PATCH + 1))  # Increment the PATCH version
          NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"  # Construct new tag
          echo "New version: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV  # Set environment variable for next steps

      - name: Create new tag and push
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          NEW_TAG: ${{ env.NEW_TAG }}
