name: Auto Versioning and Tagging

on:
  push:
    branches:
      - main
jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:  # 👈 Add this to grant write access
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "Bachhamba Khaireddine"
          git config user.email "khaireddine.bachhamba@ept.ucar.tn"

      - name: Get the latest tag (if any)
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.1.0")
          echo "Latest Tag: $TAG"
          TAG_NUM=$(echo $TAG | sed 's/v//')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$TAG_NUM"
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create new tag and push
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
        env:
          NEW_TAG: ${{ env.NEW_TAG }}
